apiVersion: v1
kind: Pod
metadata:
  name: echo-ip
  labels:
    app: echo
spec:
  container:
    - name: app
      image: ghcr.io/subicura/echo:v1
      livenessProbe:
        httpGet:
          path: /not/extist
          port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 2 #Default 1
      PeriodSeconds: 5 #Default 10
      failureThreshold: 1 #Default 3
