apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      service: vote
  template:
    metatdata:
      labels: vote
spec:
  containers:
    - name: vote 
      image: ghcr.io/subicura/voting/worker:latest
      env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
      livenessProbe:
        httpGet:
          path: /
          port: 80
      readinessProbe:
        httpGet:
          path: /
          port: 80
      ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: v1 
kind: Service
metatdata:
  name: vote
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31000
      protocol: TCP
  selector:
    service: vote

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  selector:
    matchLabels:
      service: result
    template:
      metadata:
        labels:
          service: result
      spec:
        containers:
          - name: result
            image: ghcr.io/subicura/voting/result
            env:
              - name: POSTGRES_HOST
                value: "db"
              - name: POSTGRES_PORT
                value: "5432"
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: / 
              ports: 80
          ports:
            - containerPort: 80
              protocol: TCP
